### ISSUE TITLE
Trajectory CovJSON advice

### ISSUE THREAD

**Issue by jwovens** [Reading-eScience-Centre/edal-java#140] opened 2021-07-30 13:23 UTC
Hi, I'm trying to mock up a TrajectoryFeature that I could turn in to CovJSON output, similar to that shown in the CovJSON [playground](https://covjson.org/playground/).  However I'm getting [this](https://github.com/Reading-eScience-Centre/edal-java/blob/1eb2a9231ff0bff342b20e9f8da15969a9204f5e/common/src/main/java/uk/ac/rdg/resc/edal/grid/AbstractIrregularAxis.java#L114) exception thrown if any or my axes coordinates are not always ascending.  But I can't square this with the Playground example where none of the x, y, z coordinates are entirely incrementing or decrementing.  I wonder if someone could provide some clarity?  Perhaps I'm trying to use trajectories incorrectly.  (Some runnable code to follow)

```json
{
  "type" : "Coverage",
  "domain" : {
    "type" : "Domain",
    "domainType" : "Trajectory",
    "axes": {
      "composite": {
        "dataType": "tuple",
        "coordinates": ["t","x","y","z"],
        "values": [
          ["2010-01-01T00:12:20Z", -10, 40, 5],
          ["2010-01-01T00:14:20Z", -5, 50, 4],
          ["2010-01-01T00:16:20Z", -6, 50, 5]
        ]
```

**Comment by jwovens** [comment] 2021-07-30 13:28
The instantiation of the geoPositions collection is either getting a list of coordinates where every element (t, x, y, z) is getting bigger (getOrderedGeoPositions) or a list where successive x, y, z coordinates are purely random (getRandomGeoPositions) but the time dimension is ordered.  I've played around with ordering (or not) each of the spatial coordinates and get that error thrown; I'm confused as to how a trajectory can trace a random path through space.  Many thanks for your help 😄 

```java
import org.apache.sis.referencing.CommonCRS;
import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import uk.ac.rdg.resc.edal.covjson.CoverageJsonConverter;
import uk.ac.rdg.resc.edal.covjson.CoverageJsonConverterImpl;
import uk.ac.rdg.resc.edal.domain.TrajectoryDomain;
import uk.ac.rdg.resc.edal.feature.Feature;
import uk.ac.rdg.resc.edal.feature.TrajectoryFeature;
import uk.ac.rdg.resc.edal.metadata.Parameter;
import uk.ac.rdg.resc.edal.position.GeoPosition;
import uk.ac.rdg.resc.edal.position.HorizontalPosition;
import uk.ac.rdg.resc.edal.position.VerticalCrsImpl;
import uk.ac.rdg.resc.edal.position.VerticalPosition;
import uk.ac.rdg.resc.edal.util.Array1D;
import uk.ac.rdg.resc.edal.util.ValuesArray1D;

import java.io.ByteArrayOutputStream;
import java.util.*;

public class App2 {

    private static final ByteArrayOutputStream out = new ByteArrayOutputStream();
    private static final CoverageJsonConverter converter = new CoverageJsonConverterImpl();

    public static void main(String[] args) {
        Feature<?> feature = getTrajectoryFeature(10);
        converter.checkFeatureSupported(feature);
        converter.convertFeatureToJson(out, feature);
        System.out.println(out);
    }

    private static Feature<?> getTrajectoryFeature(int trajectorySize) {

        Array1D<Number> temperature_values = new ValuesArray1D(trajectorySize);
        for (int i = 0; i < trajectorySize; i++) {
            temperature_values.set(getRandomDoubleInRange(0, 30), i);
        }

        Map<String, Array1D<Number>> valuesMap = new HashMap<>();
        valuesMap.put(getTemperatureParam().getVariableId(), temperature_values);

        Map<String, Parameter> parameterMap = new HashMap<>();
        parameterMap.put(getTemperatureParam().getVariableId(), getTemperatureParam());

        List<GeoPosition> geoPositions = getOrderedGeoPositions(trajectorySize);
//        List<GeoPosition> geoPositions = getRandomGeoPositions(trajectorySize);
        return new TrajectoryFeature(
                "some id",
                "some name",
                "some description",
                new TrajectoryDomain(
                        geoPositions
                ),
                parameterMap,
                valuesMap
        );
    }

    private static List<GeoPosition> getOrderedGeoPositions(int trajectorySize) {
        List<GeoPosition> geoPositions = new ArrayList<>();
        DateTime dt = new DateTime(2021, 7, 1, 1, 0, DateTimeZone.forID("UTC"));
        for (int i = 0; i < trajectorySize; i++) {
            geoPositions.add(
                    createTestPoint(
                            getRandomDoubleInRange(-175 + 10 * i, -175 + 10 * (i + 1)),
                            getRandomDoubleInRange(-85 + 10 * i, -85 + 10 * (i + 1)),
                            getRandomDoubleInRange(10 * i, 10 * (i + 1)),
                            dt.plusHours(i)
                    )
            );
        }
        return geoPositions;
    }

    private static List<GeoPosition> getRandomGeoPositions(int trajectorySize) {
        List<GeoPosition> geoPositions = new ArrayList<>();
        DateTime dt = new DateTime(2021, 7, 1, 1, 0, DateTimeZone.forID("UTC"));
        for (int i = 0; i < trajectorySize; i++) {
            geoPositions.add(
                    createTestPoint(
                            getRandomDoubleInRange(-175, 175),
                            getRandomDoubleInRange(-85, 85),
                            getRandomDoubleInRange(0, 100),
                            dt.plusHours(i)
                    )
            );
        }
        return geoPositions;
    }

    private static Parameter getTemperatureParam() {
        return new Parameter(
                "temperature",
                "Air Temperature",
                "temperature forecast at the location",
                "degreesC",
                "air_temperature");
    }

    static GeoPosition createTestPoint(double x, double y, double z, DateTime dt) {
        return new GeoPosition(
                new HorizontalPosition(
                        x,
                        y,
                        CommonCRS.WGS84.geographic()
                ),
                new VerticalPosition(
                        z,
                        new VerticalCrsImpl("m", false, false, true)),
                dt
        );
    }

    static double getRandomDoubleInRange(double min, double max) {
        Random r = new Random();
        return min + (max - min) * r.nextDouble();
    }
}

```

**Comment by guygriffiths** [comment] 2021-07-30 13:40
Great, thanks for the example code.  The bad news is that this is definitely a bug.  The CovJSON stuff was created for a specific project and was not all tested - I suspect you're the first person to actually convert EDAL TrajectoryFeatures to CovJSON.

If you're interested, the issue is that this is using the `ReferenceableAxis` class as an intermediary when constructing the CovJSON.  `ReferenceableAxis` (correctly) insists on monotonic co-ordinates and so isn't really a suitable thing to use.

I'll look at it now, it should be a fairly simple fix.  Are you comfortable working with snapshot releases, or will you need a `1.5.1` release to use this?

**Comment by jwovens** [comment] 2021-07-30 13:50
Thanks for such a speedy reply.  I'm in no rush so don't worry about release versions.  I'm just trying to understand the overlap between the OGC's new Environmental Data Retrieval (EDR) spec and CovJSON as an output format.  I'm sure you've seen their recent [work](https://opengeospatial.github.io/ogcapi-environmental-data-retrieval/docs/edr_api.html) on EDR.

My current use case is serving Point Feature data via API.  As this is discrete data, I'm not even sure a trajectory is useful for me, which I guess is more suited to a path through continuous data, sampling in space and time.  To add to the confusion EDR suggests an endpoint called "trajectory" which is basically an intersection with a linestring which could be 2, 3 or 4 dimensional.  But the data returned by such a query could be a point, point series, trajectory, or a collection of any of those 😄 

Knowing this specific example is a bug though unblocks my fact-finding.  Thanks for your help.

**Comment by guygriffiths** [comment] 2021-07-30 14:08
No worries, I've fixed it in the `develop` branch, so it'll be in any future releases we make.

Originally trajectory features were created for users who wanted to take arbitrary paths through (usually discrete, but hi-res) data.  Since they were (a useful) part of our data model, they got integrated into the CovJSON spec, but had never really been tested.

I'll close this now, don't hesitate to let me know if you come across any other weird things like this - if it looks broken there's a decent chance that's because it's broken :D

**Closed by guygriffiths** 2021-07-30 14:08 UTC
