### ISSUE TITLE
issue in reading GFS 0.25 data.

### ISSUE THREAD

**Issue by Khamirak** [Reading-eScience-Centre/edal-java#130] opened 2020-08-19 06:08 UTC
Hi,

Before I worked with ERA5 (grib and nc) and another data in NCWMS and all was well. But when I tried to enter GFS 0.25 data into NCWMS I retrieve the following error:

> `Status of dataset 3 (for debugging)

State: ERROR
Loading progress

Starting loading
Using dataset factory: class uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory
Error report

Stack trace:
uk.ac.rdg.resc.edal.exceptions.EdalException: Problem creating dataset 3 at /home/mostafa/Downloads/gfs2.grb
uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:131)
uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:73)
uk.ac.rdg.resc.edal.catalogue.jaxb.DatasetConfig.createDataset(DatasetConfig.java:254)
uk.ac.rdg.resc.edal.catalogue.jaxb.DatasetConfig.refresh(DatasetConfig.java:213)
uk.ac.rdg.resc.edal.catalogue.jaxb.CatalogueConfig$1.run(CatalogueConfig.java:154)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

Caused by:
java.lang.IllegalArgumentException: Coordinate values must increase or decrease monotonically
uk.ac.rdg.resc.edal.grid.AbstractIrregularAxis.checkAscending(AbstractIrregularAxis.java:114)
uk.ac.rdg.resc.edal.grid.AbstractIrregularAxis.init(AbstractIrregularAxis.java:103)
uk.ac.rdg.resc.edal.grid.AbstractIrregularAxis.<init>(AbstractIrregularAxis.java:64)
uk.ac.rdg.resc.edal.grid.TimeAxisImpl.<init>(TimeAxisImpl.java:52)
uk.ac.rdg.resc.edal.util.cdm.CdmUtils.createTimeAxis(CdmUtils.java:313)
uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory.getNonStaggeredGriddedVariableMetadata(CdmGridDatasetFactory.java:151)
uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory.generateGridDataset(CdmGridDatasetFactory.java:134)
uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory.generateDataset(CdmGridDatasetFactory.java:124)
uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:95)
uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:73)
uk.ac.rdg.resc.edal.catalogue.jaxb.DatasetConfig.createDataset(DatasetConfig.java:254)
uk.ac.rdg.resc.edal.catalogue.jaxb.DatasetConfig.refresh(DatasetConfig.java:213)
uk.ac.rdg.resc.edal.catalogue.jaxb.CatalogueConfig$1.run(CatalogueConfig.java:154)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)`

I download my data from the below link:
https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25_1hr.pl?file=gfs.t00z.pgrb2.0p25.f072&all_lev=on&all_var=on&subregion=&leftlon=52&rightlon=60&toplat=42&bottomlat=32&dir=%2Fgfs.20200819%2F00

Can you tell me what's wrong? It worth to mention that when I convert grin to netcdf, this file can be read finely in NCWMS.

Thanks for your contribution

**Comment by guygriffiths** [comment] 2020-08-25 08:41
The problem is that one of your coordinate axes is non-monotonic.  I haven't checked your data, but the usual cause of this is a wrapping longitude axis, e.g. `190, 200, 210,...340, 350, 0, 10, 20, ..., 170, 180`.  Most likely this is being taken care of when you convert to NetCDF.

**Comment by Khamirak** [comment] 2020-08-25 16:13
Thanks for your answer. Moreover I have another question. How can I define wind vector variable using U and V component data in ncWMS? 
I’ve visited the following issue, but I cannot understand how?

https://github.com/Reading-eScience-Centre/ncwms/issues/40

Could you give me an example to clarifying?

**Comment by guygriffiths** [comment] 2020-08-26 08:50
You just need to specify `standard_name` attributes on both of the component variables.  The values should have the form given in that link.  For example `eastward_windspeed` and `northward_windspeed`.

**Comment by Khamirak** [comment] 2020-08-27 06:34
Thanks, But which file have to change? Is your mean **config.xml** in the **$HOME/.ncwms2/** directory?
Could you share more information for this purpose?

**Comment by guygriffiths** [comment] 2020-08-27 08:46
You need to change your data file, so that the appropriate variables have the correct `standard_name` attributes.

**Comment by Khamirak** [comment] 2020-08-27 09:33
Thanks, I have another question:
For some reason I download ncwms version1 from the following link:
https://sourceforge.net/projects/ncwms/files/ncwms/1.2/ncWMS-1.2.war/download

I install it step by step like version 2. But in when I want to go in the **http://localhost:8080/ncWMS2/admin/** then tomcat username and password didn't work for version 1. it should be noted that version 2 was installed concurrent. It's so weird.
What's the problem do you think?

**Comment by guygriffiths** [comment] 2020-08-27 10:54
The problem is that ncWMS v1.2 didn't use the same authentication method as ncWMS2.  I _think_ it used a general Tomcat `admin` role, rather than the specific `ncWMS-admin` role. But either way, don't use v1.2, it's very out of date and we don't support it any more.

**Comment by Khamirak** [comment] 2020-08-27 14:10
Dear Blower,
I changed u10 and v10 variables standard_name attributes in  eastward_u10 and northward_u10 as attached. But this method didn't work well and when data entered into ncWMS2 I just receive two variable eastward_u10 and northward_u10.(I don't have mag and dir variable to plot wind barb and wind vector)
Could you solve my problem?


[new6.zip](https://github.com/Reading-eScience-Centre/edal-java/files/5136825/new6.zip)

**Comment by guygriffiths** [comment] 2020-08-27 14:47
You have not added a `standard_name` attribute to your variables, you have changed the variable name itself.  Additionally, you have named your variables `northward_u10` and `northward_v10`, when you need to have both a northward and an eastward component to generate a vector.

As per the link, you need to add **_an attribute_** named `standard_name`, whose value is either `eastward_wind`, or `northward_wind` (depending on which variable you add it to).  The part after the underscore (`_wind` in my example) _must be the same for both variables_.

**Comment by Khamirak** [comment] 2020-09-12 04:32
Hi Dear Guy,
I want to use **Dynamic Services** in ncWMS. I use the following configure and enter it into the ncWMS dataset


![question](https://user-images.githubusercontent.com/38399430/92987279-508fc700-f4d6-11ea-964f-5336c0b9c5ab.png)

But as you mentioned in the tutorial when I enter the following url I receive error:
[(http://192.168.229.94:8080/ncWMS2/wms?FORMAT=image%2Fpng&TRANSPARENT=TRUE&STYLES=default-scalar%2Fdefault&LAYERS=GFS/home/mostafa/Downloads/gfs/GFS1%2FHGT&TIME=2020-09-10T03%3A00%3A00.000Z&ELEVATION=350&COLORSCALERANGE=8373%2C8537&NUMCOLORBANDS=250&ABOVEMAXCOLOR=0x000000&BELOWMINCOLOR=0x000000&BGCOLOR=transparent&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A4326&BBOX=56.16,36.826666666667,60.533333333333,41.2&WIDTH=256&HEIGHT=256)]

> <ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.1" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.1.1/exceptions_1_1_1.xsd">
> <ServiceException code="LayerNotDefined"> The layer GFS/home/mostafa/Downloads/gfs/GFS1/HGT was not found on this server </ServiceException>
> </ServiceExceptionReport>


What's the problem?
Thanks

**Comment by guygriffiths** [comment] 2020-09-17 15:05
The problem is that the alias (GFS) is what refers to the location (`/home/mostaga/Downloads/gfs`), so when you request the layer `GFS/home/mostafa/Downloads/gfs/GFS1/HGT` it will look for a file named `/home/mostafa/Downloads/gfs/home/mostafa/Downloads/gfs/GFS1` containing a variable named `HGT`.

You want something more like `GFS/GFS1.nc/HGT`, assuming the file is `/home/mostafa/Downloads/gfs/GFS1.nc`, and it contains a variable named `HGT`

**Comment by Khamirak** [comment] 2020-09-19 10:38
Thanks, i've solved that.
I have another question.
I add eastward_windspeed and northward_windspeed for 10m u and v wind components. It worked finely.
Then I add these standard_name for 100m u and v wind components. But finely I had only just one wind speed and direction related to 10m u ann v components. 
How can I have at least two wind speed and direction in my netcdf file using standard_name adding?

**Comment by guygriffiths** [comment] 2020-09-22 08:39
I actually happened to fix this bug last week, and will be making a release which contains the fix at some point this week.  However, an immediate fix is to make sure that the standard names are different for each field (e.g. `eastward_windspeed_10m` and `eastward_windspeed_100m`)

**Comment by Khamirak** [comment] 2020-09-22 13:36
Hi,
Dear Guy,
1.Downloadable option in Dynamic Services don't work. I tried multiple time but when I checked downloadable checkbox and click on the save config button then, downloadable checkbox has been unchecked. What's the problem?

2. How can I change getfeatureinfo text/plain or text/html fields? for instance I wanna just shown value in popup after click

thanks

**Comment by guygriffiths** [comment] 2020-09-22 13:41
1. This is fixed, I will be releasing it soon.
2. You cannot.  Use `text/xml`, then parse it and extract just the value(s) you want.

**Comment by Khamirak** [comment] 2020-09-22 14:13
I have another question,
I insert my time as 
when I use getfeatureinfo and input time in the tilelayer.wms.extend() as **"TIME: this.wmsParams.time."** then I receive the following error:
The string undefined does not represent an ISO8601 datetime Cause: Invalid format: "undefined" 
Because time is undefined in gefeatureinfo request:
http://192.168.229.94:8080/ncWMS2/wms?REQUEST=GetFeatureInfo&SERVICE=WMS&SRS=EPSG%3A4326&TIME=undefined&STYLES=&TRANSPARENT=true&VERSION=1.1.1&FORMAT=image%2Fpng&BBOX=47.13134765625%2C32.34284135639302%2C67.47802734375001%2C42.309815415686664&HEIGHT=572&WIDTH=926&ELEVATION=500&LAYERS=GFS%2Ftestdata%2FGFS202009220000%2FABSV&QUERY_LAYERS=GFS%2Ftestdata%2FGFS202009220000%2FABSV&INFO_FORMAT=text%2Fhtml&X=464&Y=288

What's the problem do you think?

**Comment by guygriffiths** [comment] 2020-09-22 15:01
The problem is that `TIME=undefined` in the GetFeatureInfo request.  I don't know what you're using to insert value, but whatever it is, its value is undefined.

**Comment by guygriffiths** [comment] 2020-09-23 14:26
Downloadable issue fixed in https://github.com/Reading-eScience-Centre/ncwms/releases/tag/ncwms-2.5.0

**Closed by guygriffiths** 2020-09-23 14:26 UTC

**Comment by Khamirak** [comment] 2020-10-05 19:30
Dear Guy,
I used ncWMS without getfeatureinfo() option and all was well. But when I used this option for popup then I received the following error for some tile map:

> GET http://192.168.229.94:8080/ncWMS2/wms?service=WMS&request=GetMap&layers=GFS%2Ftestdata%2FGFS202009270000%2FAPCP_surface&styles=&format=image%2Fpng&transparent=true&version=1.1.1&height=256&width=256&srs=EPSG%3A3857&bbox=6261721.357121639,3757032.8142729844,6887893.492833803,4383204.949985149:1 GET http://192.168.229.94:8080/ncWMS2/wms?service=WMS&request=GetMap&layers=GFS%2Ftestdata%2FGFS202009270000%2FAPCP_surface&styles=&format=image%2Fpng&transparent=true&version=1.1.1&height=256&width=256&srs=EPSG%3A3857&bbox=6261721.357121639,3757032.8142729844,6887893.492833803,4383204.949985149 **net::ERR_INVALID_HTTP_RESPONSE**
> Image (async)
> createTile @ leaflet.js:5
> _addTile @ leaflet.js:5
> _update @ leaflet.js:5
> _setView @ leaflet.js:5
> _animateZoom @ leaflet.js:5
> fire @ leaflet.js:5
> _animateZoom @ leaflet.js:5
> (anonymous) @ leaflet.js:5
> requestAnimationFrame (async)
> f @ leaflet.js:5
> _tryAnimatedZoom @ leaflet.js:5
> setView @ leaflet.js:5
> setZoomAround @ leaflet.js:5
> _performZoom @ leaflet.js:5
> setTimeout (async)
> _onWheelScroll @ leaflet.js:5
> r @ leaflet.js:5
> 

What's the reason of this issue do you think?
My JavaScript and html code has been attached.

Cheers

[config.zip](https://github.com/Reading-eScience-Centre/edal-java/files/5329664/config.zip)

**Comment by guygriffiths** [comment] 2020-10-06 08:44
What did the request return?

**Comment by Khamirak** [comment] 2020-10-06 09:30
When I zoom in and zoom out and simultaneously I used getfeatureinfo() option, some tiles couldn't load completely.
Look at the following image:
The first image is without zoom in or zoom out that there is no problem in the console:
![complete](https://user-images.githubusercontent.com/38399430/95184094-216e2c00-07dc-11eb-8c70-6ca30ccb6dbe.png)


The second when I zoomed in some place. Some tiles couldn't load completely with the right hand error console:

![uncomplete](https://user-images.githubusercontent.com/38399430/95184118-27fca380-07dc-11eb-9f19-5247c95b4085.png)


Could you help me what's the problem?

**Comment by guygriffiths** [comment] 2020-10-06 09:37
What are those erroring requests returning?  Is it just an empty page, or is there a (partial) stacktrace?  And what errors are appearing in your Tomcat logs?

**Comment by Khamirak** [comment] 2020-10-06 09:56
In some case just an empty page returned and in some case return tiles with delay.
The important point is that when I use getfeatureinfo() option these problems released.
Today tomcat log is attached.

[localhost_access_log.2020-10-06.txt](https://github.com/Reading-eScience-Centre/edal-java/files/5332903/localhost_access_log.2020-10-06.txt)

**Comment by guygriffiths** [comment] 2020-10-06 10:01
> In some case just an empty page returned and in some case return tiles with delay.

I was confused as to why tiles would be returned, but it looks like those requests are all GetMap requests.  I thought your problem was with GetFeatureInfo requests?

Also, I don't want your entire Tomcat logs.  When you make a request which has errors, post what happens in the Tomcat logs at the moment of that request.

**Comment by Khamirak** [comment] 2020-10-06 10:41
Yes my main problem released when I used getFeatureInfo request.
I think the important point is the following error response
net::ERR_INVALID_HTTP_RESPONSE
Do you know what’s the reason of this bad response?

**Comment by Khamirak** [comment] 2020-10-06 10:44
Yes my main problem about loading GetMap request released when I used getFeatureInfo request. For more information you can look index.html that I attached in two issue later.
I think the important point is the following error response
net::ERR_INVALID_HTTP_RESPONSE
Do you know what’s the reason of this bad response?

**Comment by guygriffiths** [comment] 2020-10-06 11:01
What is happening in the Tomcat logs when you make the request which fails?  If you cannot provide me with this, I cannot help you.

**Comment by Khamirak** [comment] 2020-10-06 11:59
In the main page I just do some zoom in and zoom out. Then in some case tiles returned with delay and in some case some empty tiles returned.
the tomcat log is as follow:

[tomcat_log_error_.txt](https://github.com/Reading-eScience-Centre/edal-java/files/5333552/tomcat_log_error_.txt)

Could you help me to solve this problem?

Cheers

**Comment by guygriffiths** [comment] 2020-10-06 12:04
That looks like your client is aborting the connection.  What happens if you make those requests in a browser window?  Do they complete?

My guess would be that this is a timeout issue, and is a client-side problem.  Is there a reason you're not just using the inbuilt client (Godiva3)?

**Comment by Khamirak** [comment] 2020-10-06 13:00
Yes, when I open separately the GetMap request url with chrome browser it will be opened finely. But I don’t know what’s the reason of this error when it comes with getFeatureInfo.
It’s interesting that just some tiles returned empty or with error in zoom in and zoom out and not all of tiles.

I design GetMap request in leaflet and want to do in this platform and not openlayer interface.
Godiva3 has ran on the openlayer.

Could you give me a solution to solve my problem?

**Comment by guygriffiths** [comment] 2020-10-06 13:15
It sounds like the issue is with your client rather than ncWMS.  I've used leaflet with ncWMS in the past and have had no issues with it, so it's certainly possible to do.  My recommendation would be to use Godiva3 - if you wish to write your own interface that's fine, but I'm not able to help with debugging unless it's an ncWMS-specific issue.
