### ISSUE TITLE
ncWMS2 GetCapabilities Issue After Adding Dataset

### ISSUE THREAD

**Issue by vansant** [Reading-eScience-Centre/edal-java#29] opened 2015-09-17 19:56 UTC
Running into a WMS GetCapabilities issue after adding a dataset in ncWMS2. ncWMS2 is running on Apache Tomcat using the .war at this link https://github.com/Reading-eScience-Centre/edal-java/releases/download/edal-1.0.2/ncWMS2.war

The GetCapabilities links for 1.1.1 and 1.3.0 both work until a dataset gets added via the ncWMS admin. After the configuration is saved the dataset loads into GODIVA3 and also as PNG and KMZ files. Although, the GetCapabilities links are returning invalid XML (incomplete tags) when a dataset is available.

Youtube video demo of issue:
https://www.youtube.com/watch?v=LRbiOrogEBQ

Invalid XML document shown in video:
http://pastebin.com/QbavzNBW

Thoughts?

-VanSant

**Comment by vansant** [comment] 2015-09-17 20:40
Also, this issue is not present when using the standalone version of ncWMS2.

-VanSant

**Comment by guygriffiths** [comment] 2015-09-18 11:51
Can you provide us with the dataset you are using?  I've tried to replicate this with all of our test datasets but have been unable to get the same result.

I can however replicate the error by throwing a runtime exception when trying to get the GeographicBoundingBox of the HorizontalDomain.  I suspect that this is what's happening, but I need some data which does this in a non-artificial way to find out what the root cause is.

**Comment by vansant** [comment] 2015-09-18 16:38
Thank you for your quick response/info. Yes, two links/options for acquiring the dataset are provided below. 

Here is a direct link to download the dataset which is 2.3 GB:
http://thredds.northwestknowledge.net:8080/thredds/fileServer/NWCSC_INTEGRATED_SCENARIOS_ALL_CLIMATE/macav2livneh/bcc-csm1-1-m/macav2livneh_pr_bcc-csm1-1-m_r1i1p1_historical_1950_1969_CONUS_daily.nc

Here is a link to a NetCDF subset tool (THREDDS) where you can slice out a year or two to make the file size much smaller for downloading:
http://thredds.northwestknowledge.net:8080/thredds/ncss/grid/NWCSC_INTEGRATED_SCENARIOS_ALL_CLIMATE/macav2livneh/bcc-csm1-1-m/macav2livneh_pr_bcc-csm1-1-m_r1i1p1_historical_1950_1969_CONUS_daily.nc/dataset.html

Best,

-VanSant

**Comment by guygriffiths** [comment] 2015-09-22 10:09
Great, thanks.  I've tracked down the issue and it's fixed in the develop branch.  It was occurring when the bounding box of the data had longitudes specified in the range [0:360].  We'll do a bug-fix release soon to include this.

**Comment by vansant** [comment] 2015-09-22 18:40
Excellent news!

Thanks again,

-VanSant

**Comment by vansant** [comment] 2015-10-15 23:33
Hello,

Any news on when the bug-fix release is planned for this?

Best,

VanSant

**Comment by guygriffiths** [comment] 2015-10-20 13:00
I'm planning on doing a bugfix release Friday afernoon

**Comment by guygriffiths** [comment] 2015-10-22 08:19
I got around to this earlier than expected - it's fixed in [the latest release](https://github.com/Reading-eScience-Centre/edal-java/releases/tag/edal-1.0.3)

**Closed by guygriffiths** 2015-10-22 08:19 UTC
Labels: Bug, edal-wms
