### ISSUE TITLE
Exception using Dynamic Service

### ISSUE THREAD

**Issue by frizwi** [Reading-eScience-Centre/edal-java#91] opened 2017-06-04 23:37 UTC
I'm getting the following exception with a netCDF file set up as a Dynamic Service.

Status Code: 500
Exception:
Stacktrace:

java.io.IOException: java.lang.NullPointerException
	at uk.ac.rdg.resc.edal.wms.WmsServlet.doGet(WmsServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:104)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:45)
	at winstone.ServletConfiguration.execute(ServletConfiguration.java:249)
	at winstone.RequestDispatcher.forward(RequestDispatcher.java:335)
	at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:378)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:168)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:233)
	at winstone.FilterConfiguration.execute(FilterConfiguration.java:195)
	at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:368)
	at winstone.RequestDispatcher.forward(RequestDispatcher.java:333)
	at winstone.RequestHandlerThread.processRequest(RequestHandlerThread.java:244)
	at winstone.RequestHandlerThread.run(RequestHandlerThread.java:150)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at uk.ac.rdg.resc.edal.ncwms.NcwmsCatalogue.getDatasetFromId(NcwmsCatalogue.java:157)
	at uk.ac.rdg.resc.edal.wms.WmsServlet.getCapabilities(WmsServlet.java:673)
	at uk.ac.rdg.resc.edal.wms.WmsServlet.dispatchWmsRequest(WmsServlet.java:359)
	at uk.ac.rdg.resc.edal.ncwms.NcwmsServlet.dispatchWmsRequest(NcwmsServlet.java:210)
	at uk.ac.rdg.resc.edal.wms.WmsServlet.doGet(WmsServlet.java:292)
	... 13 more

The same file set up as a static Dataset works just fine.

Here is the link to the file that can be downloaded and tested:
http://data1.tpac.org.au/thredds/catalog/tascem/setas/catalog.html?dataset=tascem/setas/setas_simple_2017-04.nc

I've tried it both as standalone as well as running in tomcat via Hyrax - same issue.

A version of EDAL/ncWMS2 from Feb. works just fine.

**Comment by guygriffiths** [comment] 2017-06-05 08:38
Duplicate of:
https://github.com/Reading-eScience-Centre/ncwms/issues/7

Apologies for this, it's due to recent changes in the cache configuration.  It's fixed in the development branch, and will make it into a 2.2.8 release in the next few days.

**Closed by guygriffiths** 2017-06-05 08:38 UTC

**Comment by frizwi** [comment] 2017-06-05 21:47
Thanks. For now 2.2.6 is working for me

________________________________
